### PR TITLE
Make a basic README file

### LINKED ISSUE #1: Make a basic README file

### PR DESCRIPTION
**Pull request by lucasvazq**
**Basic README with logo**

font: Noto Sans Yi
color: 4a8fe0
Related Issue: #1 

Restrictions: Github doesn't allow colored text

(Edit by @bsoyka) Closes #1

### CODE REVIEW

**Comment by lucasvazq** [comment]
Can see result here: https://github.com/lucasvazq/gravify

**Comment by bsoyka** [comment]
Also, either you can add this now, or I can add this later, but this is the documentation site: https://bsoyka.gitbook.io/gravify/

**Comment by lucasvazq** [comment]
Look now, I think the "documentation" link can be more cool, but I don't know what you would like to put in

**Comment by bsoyka** [comment]
> Look now, I think the "documentation" link can be more cool, but I don't know what you would like to put in

I think that as this project matures, I’ll be able to add more information to the documentation.

**Pull request merged**
