### PR TITLE
Feature - Default images constant

### LINKED ISSUE #24: Make constant values for use with the default image parameter
Take a look at @charanjit-singh's comment [here](https://github.com/bsoyka/gravify/issues/3#issuecomment-537601348).

There are 8 different constants that need to be added in some way, and you can see them [here](https://en.gravatar.com/site/implement/images#default-image).

Please comment if you'd like to work on this, and make a pull request to the `development` branch.

### PR DESCRIPTION
**Pull request by mfaheemakhtar**
Added a static dictionary in the `Gravatar` class. The dictionary contains the 8 possible values for default images.

Resolves #24

### CODE REVIEW

**Comment by mfaheemakhtar** [comment]
BTW, docs must be updated to reflect the changes.

**Comment by mfaheemakhtar** [comment]
If the user imports the constants like this
`from gravify import Gravatar, DEFAULT_IMAGES`

`DEFAULT_IMAGES` is not self-explanatory. But the user can also alias
`from gravify import Gravatar, DEFAULT_IMAGES as GravatarDefaultImages` or something.

Thoughts?

**Comment by bsoyka** [comment]
What about `DefaultAvatars`, which is a bit more self-explanatory?

**Comment by mfaheemakhtar** [comment]
@bsoyka , `DefaultGravatars`?

And should it be `DefaultAvatars` or `DEFAULT_AVATARS`?

**Comment by bsoyka** [comment]
I think out of those three you just mentioned, `DEFAULT_AVATARS` is best.

**Pull request merged**
